force-app/main/default/objects/FieldsOnFiles_Field__mdt/FieldsOnFiles_Field__mdt.object-meta.xml
<CustomObject>
    <label>FieldsOnFiles Field</label>
    <pluralLabel>FieldsOnFiles Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/FieldsOnFiles_Field__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <label>Field</label>
    <type>Text</type>
    <fullName>Field__c</fullName>
    <length>255</length>
    <required>true</required>
    <description>The API name of the field</description>
    <inlineHelpText>The API name of the field</inlineHelpText>
</CustomField>

force-app/main/default/objects/FieldsOnFiles_Field__mdt/fields/FieldsOnFiles_Settings__c.field-meta.xml
<CustomField>
    <fullName>FieldsOnFiles_Settings__c</fullName>
    <label>FieldsOnFiles Settings</label>
    <referenceTo>FieldsOnFiles_Settings__mdt</referenceTo>
    <relationshipLabel>FieldsOnFiles Fields</relationshipLabel>
    <relationshipName>FieldsOnFiles_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FieldsOnFiles_Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>FieldsOnFiles_Fields</relationshipLabel>
    <relationshipName>FieldsOnFiles_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FieldsOnFiles_Field__mdt/fields/Show_on_Related_List__c.field-meta.xml
<CustomField>
    <fullName>Show_on_Related_List__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show on Related List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldsOnFiles_Field__mdt/fields/Show_on_Upload_Form__c.field-meta.xml
<CustomField>
    <fullName>Show_on_Upload_Form__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show on Upload Form</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldsOnFiles_Settings__mdt/FieldsOnFiles_Settings__mdt.object-meta.xml
<CustomObject>
    <label>FieldsOnFiles Settings</label>
    <pluralLabel>FieldsOnFiles Settings</pluralLabel>
    <description>added from sfdx plugin</description>
</CustomObject>

force-app/main/default/objects/FieldsOnFiles_Settings__mdt/fields/Display_Sharing__c.field-meta.xml
<CustomField>
    <label>Display Sharing</label>
    <type>Checkbox</type>
    <fullName>Display_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/FieldsOnFiles_Settings__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>FieldsOnFiles_Settings</relationshipLabel>
    <relationshipName>FieldsOnFiles_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieldsOnFiles_Settings__mdt/fields/Show_Preview__c.field-meta.xml
<CustomField>
    <label>Show Preview</label>
    <type>Checkbox</type>
    <fullName>Show_Preview__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/classes/fieldsOnFiles.cls
public with sharing class fieldsOnFiles {
  @AuraEnabled(cacheable=true)
  public static string getSerialized(string objectName) {
    return JSON.serialize(
      [
        SELECT
          MasterLabel,
          Display_Sharing__c,
          Object__c,
          Show_Preview__c,
          (
            SELECT Field__c, Show_on_Related_List__c, Show_on_Upload_Form__c
            FROM FieldsOnFiles_Fields__r
          )
        FROM FieldsOnFiles_Settings__mdt
        WHERE Object__c = :objectName
        LIMIT 1
      ]
    );
  }

  @auraEnabled(cacheable=true)
  public static Id getCVId(id ContentDocumentId) {
    return [
      SELECT id
      FROM ContentVersion
      WHERE IsLatest = true AND ContentDocumentId = :ContentDocumentId
    ]
    .id;
  }
}